openapi: 3.1.0
info:
  title: GPT Orchestration API – Market GAP Analysis
  version: 1.1.0
  description: Receives IT assessment output from GPT2 and initiates Market GAP Analysis.

servers:
  - url: https://gpt-api-server-7wu8.onrender.com

paths:
  /receive_request:
    post:
      operationId: receiveGPTRequest
      summary: Receive results from GPT2 for Market GAP Analysis
      description: >
        Accepts outputs from the IT Assessment module (GPT2) and triggers Market GAP Analysis.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  example: Temp_20250521_user@example.com
                gpt_module:
                  type: string
                  enum: [it_assessment]
                files:
                  type: array
                  items:
                    type: object
                    properties:
                      file_name:
                        type: string
                      file_url:
                        type: string
                        format: uri
                    required:
                      - file_name
                      - file_url
                source:
                  type: string
                  example: it_assessment
                next_action_webhook:
                  type: string
                  format: uri
                  example: https://hook.us2.make.com/w7xafp1yx69vhb13t7yc5aduru4i9l4i
              required:
                - session_id
                - gpt_module
                - files
                - next_action_webhook
      responses:
        "200":
          description: GPT2 output received for Market GAP Analysis
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Market GAP Analysis started

  /send_result:
    post:
      operationId: sendGPTResult
      summary: Send Market GAP result to next module
      description: Posts generated analysis outputs to the next module webhook.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                gpt_module:
                  type: string
                  enum: [gap_market]
                status:
                  type: string
                  example: complete
                message:
                  type: string
                file_1_name:
                  type: string
                file_1_url:
                  type: string
                  format: uri
                file_2_name:
                  type: string
                file_2_url:
                  type: string
                  format: uri
              required:
                - session_id
                - gpt_module
                - status
                - file_1_name
                - file_1_url
      responses:
        "200":
          description: Market GAP output successfully posted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Files delivered to next module

  /notify_zip_delivery:
    post:
      operationId: notifyZipDelivery
      summary: Notify session completion and ZIP delivery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                zip_url:
                  type: string
              required:
                - session_id
                - zip_url
      responses:
        "200":
          description: ZIP delivery acknowledged
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: >-
                      Final ZIP sent. Reports delivered successfully and session closed.
