openapi: 3.1.0
info:
  title: Generate IT Assessment Reports
  version: 1.5.2
  description: >
    Generates DOCX and PPTX reports for an IT session based on scoring, findings, and recommendations.

servers:
  - url: https://docx-generator-api.onrender.com

paths:
  /generate_assessment:
    post:
      operationId: generateAssessmentReports
      summary: Generate DOCX and PPTX reports from assessment data
      description: >
        Produces two deliverables for an IT session:

        1. A DOCX report with detailed infrastructure assessment.
        2. A PPTX presentation summarizing insights and recommendations.

        Files are stored in a session-specific folder.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  description: Unique folder/session identifier (e.g., Temp_YYYYMMDD_email_com)
                  example: Temp_20250522_user_example_com
                score_summary:
                  type: string
                  description: Summary of infrastructure scoring (e.g., Excellent, Obsolete)
                  example: "Excellent: 20%, Advanced: 40%, Standard: 30%, Obsolete: 10%"
                recommendations:
                  type: string
                  description: Summary of modernization actions (cloud migration, refresh, etc.)
                  example: "Decommission Tier 1 servers and migrate Tier 2 workloads to Azure."
                key_findings:
                  type: string
                  description: Optional business-level observations (SLA risks, legacy exposure)
                  example: "Several critical systems run on unsupported platforms, posing risks."
              required:
                - session_id
                - score_summary
                - recommendations
      responses:
        "200":
          description: URLs to the generated DOCX and PPTX files
          content:
            application/json:
              schema:
                type: object
                properties:
                  docx_url:
                    type: string
                    description: Public URL of the generated DOCX report
                    example: https://docx-generator-api.onrender.com/files/Temp_20250522_user_example_com/IT_Current_Status_Assessment_Report.docx
                  pptx_url:
                    type: string
                    description: Public URL of the generated PowerPoint summary
                    example: https://docx-generator-api.onrender.com/files/Temp_20250522_user_example_com/IT_Current_Status_Executive_Report.pptx
        "400":
          description: Missing or invalid input
        "500":
          description: Internal error while generating reports
