openapi: 3.1.0
info:
  title: Generate Assessment Report
  version: 1.0.0

servers:
  - url: https://docx-generator-api.onrender.com

paths:
  /generate_assessment:
    post:
      operationId: generateAssessmentDoc
      summary: Generate assessment_<session_id>.docx and assessment_<session_id>.pptx
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                score_summary:
                  type: string
                recommendations:
                  type: string
                key_findings:
                  type: string
              required:
                - session_id
                - score_summary
                - recommendations
      responses:
        "200":
          description: Assessment files successfully generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  docx_url:
                    type: string
                  pptx_url:
                    type: string
