openapi: 3.1.0
info:
  title: Generate IT Assessment Reports
  version: 1.5.0
  description: >
    This API generates a DOCX report and PPTX executive summary for an IT assessment session.
    The output is based on tier distribution analysis, modernization recommendations, and strategic insights.

servers:
  - url: https://docx-generator-api.onrender.com

paths:
  /generate_assessment:
    post:
      operationId: generateAssessmentReports
      summary: Generate DOCX and PPTX reports based on IT assessment scoring
      description: >
        Generates two deliverables for a given IT modernization session:
        1. A Word document (DOCX) containing a detailed current-state infrastructure assessment with visuals.
        2. A PowerPoint presentation (PPTX) summarizing executive insights, tier distribution, and modernization highlights.

        All files are generated and stored in a folder identified by the session_id.

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  description: >
                    Unique session identifier, used to determine the storage folder for generated documents.
                    Must begin with 'Temp_' and be unique for each request.
                  example: Temp_20250521_user_example_com
                score_summary:
                  type: string
                  description: >
                    Summary of infrastructure scoring by tier (e.g., Excellent, Advanced, Standard, Obsolete).
                  example: "Excellent: 20%, Advanced: 40%, Standard: 30%, Obsolete: 10%"
                recommendations:
                  type: string
                  description: >
                    Summary of modernization recommendations including actions such as cloud migration, hardware upgrades,
                    or workload redistribution.
                  example: "Decommission Tier 1 servers and migrate Tier 2 workloads to Azure."
                key_findings:
                  type: string
                  description: >
                    Optional business-level observations for executive awareness (e.g., security risks, compliance gaps).
                  example: "Several critical systems run on unsupported platforms, posing business continuity risks."
              required:
                - session_id
                - score_summary
                - recommendations

      responses:
        "200":
          description: URLs to the generated DOCX and PPTX files
          content:
            application/json:
              schema:
                type: object
                properties:
                  docx_url:
                    type: string
                    description: Public link to the generated Word document
                    example: https://docx-generator-api.onrender.com/files/Temp_20250521_user_example_com/IT_Current_Status_Assessment_Report.docx
                  pptx_url:
                    type: string
                    description: Public link to the generated PowerPoint presentation
                    example: https://docx-generator-api.onrender.com/files/Temp_20250521_user_example_com/IT_Current_Status_Executive_Report.pptx
