openapi: 3.1.0
info:
  title: Generate IT Assessment Reports
  version: 1.3.0
  description: >
    This API generates a DOCX report and PPTX executive summary for an IT assessment session.
    The output is based on tier distribution, modernization recommendations, and summary insights.

servers:
  - url: https://docx-generator-api.onrender.com

paths:
  /generate_assessment:
    post:
      operationId: generateAssessmentReports
      summary: Generate DOCX and PPTX from IT scoring and recommendations
      description: >
        Takes session-specific insights and produces two deliverables:
        - A Word document with current state analysis and visual tier chart
        - A PowerPoint executive summary
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  description: Unique session ID used to store output (with or without Temp_ prefix)
                  example: Temp_20250519_user_example_com
                score_summary:
                  type: string
                  description: Summary of infrastructure scoring results (e.g., tier breakdowns, readiness scores)
                  example: "Excellent: 15%, Advanced: 35%, Standard: 30%, Obsolete: 20%"
                recommendations:
                  type: string
                  description: AI-generated transformation advice based on the data
                  example: "Migrate legacy workloads to cloud and decommission Tier 1 hardware."
                key_findings:
                  type: string
                  description: Optional business or executive findings
                  example: "Tier 3 hardware underpins critical applications with high SLA impact."
              required:
                - session_id
                - score_summary
                - recommendations
      responses:
        "200":
          description: Generated DOCX and PPTX URLs returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  docx_url:
                    type: string
                    description: Publicly accessible DOCX report URL
                    example: https://docx-generator-api.onrender.com/files/Temp_20250519_user_example_com/IT_Current_Status_Assessment_Report.docx
                  pptx_url:
                    type: string
                    description: Publicly accessible PPTX summary URL
                    example: https://docx-generator-api.onrender.com/files/Temp_20250519_user_example_com/IT_Current_Status_Executive_Report.pptx
