openapi: 3.1.0
info:
  title: Generate IT Assessment Reports
  version: 1.1.0
  description: >
    This API generates a DOCX and PPTX summary based on IT assessment data
    including infrastructure scoring, modernization readiness, and executive insights.

servers:
  - url: https://docx-generator-api.onrender.com

paths:
  /generate_assessment:
    post:
      operationId: generateAssessmentDoc
      summary: Generate assessment report and executive summary presentation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  description: Session identifier used for file naming and storage
                  example: Temp_20250519_abc@example.com
                score_summary:
                  type: string
                  description: Summary of scoring results from the gap analysis (e.g., tier distribution, readiness scores)
                  example: "25% Excellent, 45% Standard, 30% Obsolete"
                recommendations:
                  type: string
                  description: Recommendations for modernization (e.g., upgrade obsolete, migrate to cloud)
                  example: "Replace 60% of obsolete servers; consolidate Tier 2 data centers"
                key_findings:
                  type: string
                  description: Optional executive-level insights
                  example: "Legacy ERP servers show critical performance issues under load."
              required:
                - session_id
                - score_summary
                - recommendations
      responses:
        "200":
          description: Assessment DOCX and PPTX files successfully generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  docx_url:
                    type: string
                    description: Public URL to download the assessment DOCX
                  pptx_url:
                    type: string
                    description: Public URL to download the executive summary PPTX
