openapi: 3.1.0
info:
  title: Generate IT Assessment Reports
  version: 1.1.0
  description: >
    This API generates a DOCX and PPTX summary based on IT assessment data
    including infrastructure scoring, modernization readiness, and executive insights.

servers:
  - url: https://docx-generator-api.onrender.com

paths:
  /generate_assessment:
    post:
      operationId: generateAssessmentDoc
      summary: Generate IT_Current_Status_Assessment_<session_id>.docx and IT_Infrastructure_Assessment_Executive_Summary_<session_id>.pptx
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  description: Session identifier used for file naming and storage
                score_summary:
                  type: string
                  description: Summary of scoring results from the gap analysis (e.g., tier distribution, readiness scores)
                recommendations:
                  type: string
                  description: Recommendations for modernization based on analysis (e.g., replace obsolete, cloudify, consolidate)
                key_findings:
                  type: string
                  description: Optional executive findings (e.g., top concerns, infrastructure risks, standout systems)
              required:
                - session_id
                - score_summary
                - recommendations
      responses:
        "200":
          description: Assessment DOCX and PPTX files successfully generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  docx_url:
                    type: string
                    description: Public URL to download the IT_Current_Status_Assessment_<session_id>.docx
                  pptx_url:
                    type: string
                    description: Public URL to download the IT_Infrastructure_Assessment_Executive_Summary_<session_id>.pptx
