openapi: 3.1.0
info:
  title: Generate IT Assessment Reports
  version: 1.4.0
  description: >
    This API generates a DOCX report and PPTX executive summary for an IT assessment session.
    The output is based on tier distribution analysis, modernization recommendations, and strategic insights.

servers:
  - url: https://docx-generator-api.onrender.com

paths:
  /generate_assessment:
    post:
      operationId: generateAssessmentReports
      summary: Generate DOCX and PPTX from IT scoring and recommendations
      description: >
        Generates two deliverables for a given IT modernization session:
        1. A Word document (DOCX) providing a detailed current-state assessment with visual charts.
        2. A PowerPoint deck (PPTX) summarizing the key executive highlights and tier recommendations.

        All files are stored in the folder associated with the session_id.

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  description: >
                    Unique session ID used to determine storage folder for generated files.
                    Should begin with 'Temp_' and be unique per session.
                  example: Temp_20250521_user_example_com
                score_summary:
                  type: string
                  description: >
                    High-level breakdown of scoring results across tiers (e.g., Excellent, Advanced, Standard, Obsolete).
                  example: "Excellent: 15%, Advanced: 35%, Standard: 30%, Obsolete: 20%"
                recommendations:
                  type: string
                  description: >
                    AI-generated modernization advice, including infrastructure upgrades, cloud adoption, or decommissioning steps.
                  example: "Migrate legacy workloads to AWS and decommission obsolete Tier 1 physical servers."
                key_findings:
                  type: string
                  description: >
                    Optional high-level business observations or risks from the assessment, suitable for executive briefings.
                  example: "Critical business systems rely on end-of-life hardware, increasing SLA and security risks."
              required:
                - session_id
                - score_summary
                - recommendations

      responses:
        "200":
          description: Generated report URLs returned successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  docx_url:
                    type: string
                    description: Public URL of the generated Word report
                    example: https://docx-generator-api.onrender.com/files/Temp_20250521_user_example_com/IT_Current_Status_Assessment_Report.docx
                  pptx_url:
                    type: string
                    description: Public URL of the generated PowerPoint summary
                    example: https://docx-generator-api.onrender.com/files/Temp_20250521_user_example_com/IT_Current_Status_Executive_Report.pptx
