openapi: 3.1.0
info:
  title: GPT Orchestration API
  version: 1.1.0

servers:
  - url: https://gpt-api-server-7wu8.onrender.com

paths:
  /receive_request:
    post:
      operationId: receiveGPTRequest
      summary: Trigger a GPT module task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  description: Unique session identifier
                email:
                  type: string
                  format: email
                  description: User's email address
                gpt_module:
                  type: string
                  enum:
                    - it_advisor
                    - it_assessment
                    - gap_market
                    - it_strategy
                    - gap_target
                    - it_compliance
                    - roadmap
                    - it_financials
                files:
                  type: array
                  description: List of uploaded files
                  items:
                    type: object
                    properties:
                      file_name:
                        type: string
                        description: Name of the uploaded file
                      file_url:
                        type: string
                        format: uri
                        description: Public URL to access the file
                      type:
                        type: string
                        description: Logical classification (e.g., asset_inventory)
                        example: asset_inventory
                    required:
                      - file_name
                      - file_url
                      - type
                source:
                  type: string
                  description: Source module triggering the request
                next_action_webhook:
                  type: string
                  format: uri
                  description: Webhook URL for the next GPT action
              required:
                - session_id
                - email
                - gpt_module
                - files
                - next_action_webhook
      responses:
        "200":
          description: GPT request received
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /send_result:
    post:
      operationId: sendGPTResult
      summary: Submit GPT module result
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                gpt_module:
                  type: string
                  enum:
                    - it_assessment
                    - gap_market
                    - it_strategy
                    - gap_target
                    - it_compliance
                    - roadmap
                    - it_financials
                file_name:
                  type: string
                  description: Name of the primary result file
                file_url:
                  type: string
                  format: uri
                  description: URL to download the primary result file
                file_2_name:
                  type: string
                  description: Name of the secondary file (optional)
                file_2_url:
                  type: string
                  format: uri
                  description: URL to download the secondary file (optional)
                status:
                  type: string
                  description: Status of processing
                  example: complete
                message:
                  type: string
                  description: Optional message or error details
                  example: Missing asset inventory file for assessment
              required:
                - session_id
                - gpt_module
                - file_name
                - file_url
                - status
      responses:
        "200":
          description: GPT result posted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /notify_zip_delivery:
    post:
      operationId: notifyZipDelivery
      summary: Notify user of ZIP delivery and end of session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                zip_url:
                  type: string
                  format: uri
              required:
                - session_id
                - zip_url
      responses:
        "200":
          description: ZIP delivery notification sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: >
                      Please find the link to download your IT Transformation reports. This session has now ended and the Google Drive along with all the reports that you uploaded and were generated have been deleted. A copy of this zipped file has been emailed to you also. In case you have any questions on the reports, request you to please upload the report files in this chat for me to review and provide insights.
