openapi: 3.1.0
info:
  title: GPT Orchestration API – IT Advisor (via Proxy)
  version: 3.1.0

servers:
  - url: https://gpt1-proxy.onrender.com

paths:
  /start_analysis:
    post:
      operationId: startAnalysis
      summary: Initialize session and Google Drive folder
      description: |
        Starts a new GPT1 session by generating a session ID, creating a Google Drive folder, and updating the session tracker.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                goal:
                  type: string
              required:
                - email
                - goal
      responses:
        "200":
          description: Session initialized and folder URL returned.
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_id:
                    type: string
                  folder_url:
                    type: string
                    format: uri

  /start_assessment:
    post:
      operationId: startAssessment
      summary: Trigger GPT2 for IT Assessment using uploaded files
      description: |
        Triggers GPT2 by sending the list of uploaded files from the session-specific folder along with session details.
        Each file must include a correctly classified `type` such as 'asset_inventory', 'log', etc.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                email:
                  type: string
                  format: email
                goal:
                  type: string
                files:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    properties:
                      file_name:
                        type: string
                      file_url:
                        type: string
                        format: uri
                      type:
                        type: string
                        enum:
                          - asset_inventory
                          - intake
                          - gap_working
                          - log
                    required:
                      - file_name
                      - file_url
                      - type
              required:
                - session_id
                - email
                - goal
                - files
      responses:
        "200":
          description: GPT2 triggered successfully for assessment.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: GPT2 started
