openapi: 3.1.0
info:
  title: GPT Orchestration API – IT Assessment Module
  version: 1.2.0
  description: API definition for triggering, handling, and posting results from the IT Assessment GPT module.

servers:
  - url: https://gpt-api-server-7wu8.onrender.com

paths:
  /receive_request:
    post:
      operationId: receiveGPTRequest
      summary: Trigger a GPT module task
      description: Initiates a GPT module using the provided session details and file metadata.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  description: Unique session identifier (e.g., Temp_YYYYMMDDHHMM_email)
                  example: Temp_051620252201_user@example.com
                email:
                  type: string
                  format: email
                  description: User's email address
                  example: user@example.com
                gpt_module:
                  type: string
                  enum:
                    - it_advisor
                    - it_assessment
                    - gap_market
                    - it_strategy
                    - gap_target
                    - it_compliance
                    - roadmap
                    - it_financials
                  description: GPT module being triggered
                  example: it_assessment
                files:
                  type: array
                  description: List of files associated with this session
                  items:
                    type: object
                    properties:
                      file_name:
                        type: string
                        description: Name of the uploaded file
                        example: asset_inventory.csv
                      file_url:
                        type: string
                        format: uri
                        description: Publicly accessible file URL
                        example: https://example.com/asset_inventory.csv
                      type:
                        type: string
                        description: Classification type of the file
                        example: asset_inventory
                    required:
                      - file_name
                      - file_url
                      - type
                source:
                  type: string
                  description: Origin module or system that triggered this request
                  example: it_advisor
                next_action_webhook:
                  type: string
                  format: uri
                  description: Webhook endpoint to send the results to
                  example: https://hook.us2.make.com/next_action_webhook
              required:
                - session_id
                - email
                - gpt_module
                - files
                - next_action_webhook
      responses:
        "200":
          description: GPT request received successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Assessment started

  /send_result:
    post:
      operationId: sendGPTResult
      summary: Submit GPT module result
      description: Posts the result files generated by the GPT module to the next webhook in the chain.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  description: Unique session ID
                  example: Temp_051620252201_user@example.com
                gpt_module:
                  type: string
                  enum:
                    - it_assessment
                    - gap_market
                    - it_strategy
                    - gap_target
                    - it_compliance
                    - roadmap
                    - it_financials
                  description: Module that generated the result
                  example: it_assessment
                file_name:
                  type: string
                  description: Name of the main output file
                  example: Assessment_GAP_Working_Temp_051620252201_user@example.com.xlsx
                file_url:
                  type: string
                  format: uri
                  description: URL to download the main result file
                  example: https://api.example.com/files/Assessment_GAP_Working_Temp_051620252201_user@example.com.xlsx
                file_2_name:
                  type: string
                  description: Name of the optional second file
                  example: Assessment_Summary_Deck_Temp_051620252201_user@example.com.pptx
                file_2_url:
                  type: string
                  format: uri
                  description: URL to download the optional second result file
                  example: https://api.example.com/files/Assessment_Summary_Deck_Temp_051620252201_user@example.com.pptx
                status:
                  type: string
                  description: Status of the process
                  example: complete
                message:
                  type: string
                  description: Optional error or informational message
                  example: Missing asset inventory file for assessment
              required:
                - session_id
                - gpt_module
                - file_name
                - file_url
                - status
      responses:
        "200":
          description: GPT result posted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Results successfully posted

  /notify_zip_delivery:
    post:
      operationId: notifyZipDelivery
      summary: Notify user of ZIP delivery and session closure
      description: Final step in the GPT workflow that notifies the user about ZIP delivery and cleanup.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  description: Unique session ID
                  example: Temp_051620252201_user@example.com
                zip_url:
                  type: string
                  format: uri
                  description: URL for the final ZIP package
                  example: https://api.example.com/files/final_bundle.zip
              required:
                - session_id
                - zip_url
      responses:
        "200":
          description: ZIP delivery notification sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: >
                      Please find the link to download your IT Transformation reports. This session has now ended and the Google Drive along with all the reports that you uploaded and were generated have been deleted. A copy of this zipped file has been emailed to you also. In case you have any questions on the reports, request you to please upload the report files in this chat for me to review and provide insights.
