openapi: 3.1.0
info:
  title: GPT Orchestration API – IT Assessment Module
  version: 1.6.0
  description: >
    API for receiving IT assessment requests from GPT1, analyzing infrastructure files,
    and forwarding output files to the next GPT (e.g., Market GAP Analysis).

servers:
  - url: https://it-assessment-api.onrender.com

paths:
  /receive_request:
    post:
      operationId: receiveGPTRequest
      summary: Trigger IT Assessment processing
      description: >
        Starts the IT Assessment module using session metadata and uploaded infrastructure files.
        Output files are forwarded to the next_action_webhook (e.g., Market GAP Analysis).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  description: Unique session ID (e.g., Temp_20250520_user@example.com)
                email:
                  type: string
                  format: email
                  description: User's email address
                gpt_module:
                  type: string
                  enum: [it_assessment]
                  description: Module identifier
                files:
                  type: array
                  description: List of input files
                  minItems: 1
                  items:
                    type: object
                    properties:
                      file_name:
                        type: string
                        description: Original name of uploaded file
                      file_url:
                        type: string
                        format: uri
                        description: URL pointing to downloadable file
                      type:
                        type: string
                        enum:
                          - asset_inventory
                          - gap_working
                          - intake
                          - log
                        description: File classification type
                    required:
                      - file_name
                      - file_url
                      - type
                source:
                  type: string
                  description: Origin GPT module (e.g., it_advisor)
                next_action_webhook:
                  type: string
                  format: uri
                  description: Webhook URL to which output will be posted after assessment
              required:
                - session_id
                - email
                - gpt_module
                - files
                - next_action_webhook
      responses:
        "200":
          description: IT Assessment request accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Assessment started

  /send_result:
    post:
      operationId: sendGPTResult
      summary: Send output files to next GPT module
      description: >
        Delivers DOCX, PPTX, and XLSX outputs to the webhook of the next module
        such as Market GAP Analysis or IT Strategy.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                gpt_module:
                  type: string
                  enum: [it_assessment]
                status:
                  type: string
                  example: complete
                message:
                  type: string
                  description: Optional message about status or results
                file_1_name:
                  type: string
                file_1_url:
                  type: string
                  format: uri
                file_2_name:
                  type: string
                file_2_url:
                  type: string
                  format: uri
                file_3_name:
                  type: string
                file_3_url:
                  type: string
                  format: uri
                file_4_name:
                  type: string
                file_4_url:
                  type: string
                  format: uri
              required:
                - session_id
                - gpt_module
                - status
                - file_1_name
                - file_1_url
      responses:
        "200":
          description: Files successfully delivered
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Files uploaded and status acknowledged

  /notify_zip_delivery:
    post:
      operationId: notifyZipDelivery
      summary: Final ZIP delivery notification
      description: >
        Informs the system that the full bundle ZIP has been delivered to the user and the session can be marked complete.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                zip_url:
                  type: string
                  format: uri
              required:
                - session_id
                - zip_url
      responses:
        "200":
          description: ZIP delivery acknowledged
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Final ZIP delivered and session closed
