openapi: 3.1.0
info:
  title: GPT Orchestration API - IT Advisor (via Proxy)
  version: 1.2.0

servers:
  - url: https://gpt1-proxy.onrender.com

paths:
  /start_session:
    post:
      operationId: startSession
      summary: Start session by sending user email via Flask proxy to Make.com
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
              required:
                - email
      responses:
        "200":
          description: Session started successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /receive_request:
    post:
      operationId: receiveGPTRequest
      summary: Trigger a GPT module task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                gpt_module:
                  type: string
                  enum:
                    - it_advisor
                    - it_assessment
                    - gap_market
                    - it_strategy
                    - gap_target
                    - it_compliance
                    - roadmap
                    - it_financials
                files:
                  type: array
                  items:
                    type: object
                    properties:
                      file_name:
                        type: string
                      file_url:
                        type: string
                        format: uri
                      type:
                        type: string
                    required:
                      - file_name
                      - file_url
                      - type
                source:
                  type: string
                next_action_webhook:
                  type: string
                  format: uri
              required:
                - session_id
                - gpt_module
                - files
                - next_action_webhook
      responses:
        "200":
          description: GPT task initiated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /send_result:
    post:
      operationId: sendGPTResult
      summary: Submit GPT module result
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                gpt_module:
                  type: string
                  enum:
                    - it_advisor
                    - it_assessment
                    - gap_market
                    - it_strategy
                    - gap_target
                    - it_compliance
                    - roadmap
                    - it_financials
                file_name:
                  type: string
                file_url:
                  type: string
                  format: uri
                file_2_name:
                  type: string
                file_2_url:
                  type: string
                  format: uri
                status:
                  type: string
                  example: complete
                message:
                  type: string
              required:
                - session_id
                - gpt_module
                - file_name
                - file_url
                - status
      responses:
        "200":
          description: GPT result received
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /notify_zip_delivery:
    post:
      operationId: notifyZipDelivery
      summary: Notify user of ZIP delivery and close session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                zip_url:
                  type: string
                  format: uri
              required:
                - session_id
                - zip_url
      responses:
        "200":
          description: ZIP notification delivered
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: >
                      Please find the link to download your IT Transformation reports. This session has now ended and the Google Drive along with all the reports that you uploaded and were generated have been deleted. A copy of this zipped file has been emailed to you also. In case you have any questions on the reports, request you to please upload the report files in this chat for me to review and provide insights.
