openapi: 3.1.0
info:
  title: GPT Orchestration API – IT Assessment Module
  version: 1.2.1
  description: API definition for triggering, handling, and posting results from the IT Assessment GPT module.

servers:
  - url: https://gpt-api-server-7wu8.onrender.com

paths:
  /receive_request:
    post:
      operationId: receiveGPTRequest
      summary: Trigger the IT Assessment GPT module
      description: Initiates IT assessment using provided session ID and associated infrastructure files.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  description: Unique session identifier (e.g., Temp_YYYYMMDDHHMM_email)
                  example: Temp_202505191345_user@example.com
                email:
                  type: string
                  format: email
                  description: User’s email address
                  example: user@example.com
                gpt_module:
                  type: string
                  enum:
                    - it_advisor
                    - it_assessment
                    - gap_market
                    - it_strategy
                    - gap_target
                    - it_compliance
                    - roadmap
                    - it_financials
                  description: GPT module being invoked
                  example: it_assessment
                files:
                  type: array
                  minItems: 1
                  description: List of files to be processed
                  items:
                    type: object
                    properties:
                      file_name:
                        type: string
                        description: File name
                        example: Asset Inventory.xlsx
                      file_url:
                        type: string
                        format: uri
                        description: Public URL of the uploaded file
                        example: https://drive.google.com/xyz/asset.xlsx
                      type:
                        type: string
                        description: File classification
                        example: asset_inventory
                    required:
                      - file_name
                      - file_url
                      - type
                source:
                  type: string
                  description: Origin of the trigger (e.g., GPT1)
                  example: it_advisor
                next_action_webhook:
                  type: string
                  format: uri
                  description: Webhook endpoint to POST results to
                  example: https://hook.us2.make.com/next_module_webhook
              required:
                - session_id
                - gpt_module
                - files
                - next_action_webhook
      responses:
        "200":
          description: GPT task accepted and started
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Started it_assessment module for session Temp_202505191345_user@example.com

  /send_result:
    post:
      operationId: sendGPTResult
      summary: Submit GPT result files to next module
      description: Sends output files (Excel, DOCX, PPTX) generated by this module to the next webhook.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  description: Session identifier
                gpt_module:
                  type: string
                  enum:
                    - it_assessment
                    - gap_market
                    - it_strategy
                    - gap_target
                    - it_compliance
                    - roadmap
                    - it_financials
                  description: Module generating the result
                file_name:
                  type: string
                  description: Main output file name
                file_url:
                  type: string
                  format: uri
                  description: URL for the primary file
                file_2_name:
                  type: string
                  description: Optional second file
                file_2_url:
                  type: string
                  format: uri
                  description: URL for optional second file
                status:
                  type: string
                  example: complete
                message:
                  type: string
                  description: Any notes or warnings
              required:
                - session_id
                - gpt_module
                - file_name
                - file_url
                - status
      responses:
        "200":
          description: Results posted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Results successfully posted

  /notify_zip_delivery:
    post:
      operationId: notifyZipDelivery
      summary: Notify final ZIP delivery
      description: Notifies the user that all reports have been delivered as a ZIP package and cleanup is complete.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                zip_url:
                  type: string
                  format: uri
              required:
                - session_id
                - zip_url
      responses:
        "200":
          description: Notification sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: >
                      ZIP delivered and session cleanup completed. A download link has been emailed to the user.
