openapi: 3.1.0
info:
  title: IT Advisor Actions
  version: 1.0.0
  servers:
  - url: https://gpt1-proxy.onrender.com
paths:
  /start_analysis:
    post:
      summary: Start session and create temp folder
      operationId: start_analysis
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                goal:
                  type: string
              required:
                - email
                - goal
      responses:
        '200':
          description: Session created

  /list_files:
    post:
      summary: List and classify uploaded files
      operationId: list_files
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                email:
                  type: string
              required:
                - session_id
                - email
      responses:
        '200':
          description: File list returned

  /user_message:
    post:
      summary: Watch for upload confirmation to trigger assessment
      operationId: start_assessment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                message:
                  type: string
              required:
                - session_id
                - message
      responses:
        '200':
          description: Assessment triggered or waiting
