openapi: 3.1.0
info:
  title: GPT Orchestration API – IT Advisor (via Proxy)
  version: 2.5.0

servers:
  - url: https://gpt1-proxy.onrender.com

paths:
  /upload_to_drive:
    post:
      operationId: uploadToDrive
      summary: Upload a file to Google Drive via Flask backend
      description: |
        Uploads a file from GPT1 and stores it in the shared Google Drive temp folder.
      x-openai-form-data-parameters:
        - name: file
          type: file
          required: true
        - name: email
          type: string
          required: true
        - name: type
          type: string
          required: false
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                email:
                  type: string
                type:
                  type: string
              required:
                - file
                - email
      responses:
        "200":
          description: File successfully uploaded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  file_name:
                    type: string
                  file_url:
                    type: string
                    format: uri
                  email:
                    type: string
                  type:
                    type: string
