openapi: 3.1.0
info:
  title: GPT Orchestration API – IT Assessment Module
  version: 1.8.0
  description: >
    API for receiving IT assessment requests from GPT1, analyzing infrastructure files,
    and forwarding output files to the next GPT module (e.g., Market GAP Analysis).

servers:
  - url: https://it-assessment-api.onrender.com

paths:
  /start_assessment:
    post:
      operationId: startAssessment
      summary: Start IT Assessment processing
      description: >
        Receives session metadata and infrastructure files from GPT1 and
        initiates asynchronous assessment. Output results will be sent to the next GPT API endpoint.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  description: Unique session ID (e.g., Temp_20250521_user@example.com)
                email:
                  type: string
                  format: email
                  description: User's email address
                goal:
                  type: string
                  description: Free-text goal description
                files:
                  type: array
                  minItems: 1
                  description: List of uploaded infrastructure files
                  items:
                    type: object
                    properties:
                      file_name:
                        type: string
                      file_url:
                        type: string
                        format: uri
                      type:
                        type: string
                        enum:
                          - asset_inventory
                          - gap_working
                          - intake
                          - log
                          - capacity_plan
                          - compliance_report
                          - firewall_rules
                          - backup_schedule
                          - strategy_input
                          - general
                    required:
                      - file_name
                      - file_url
                      - type
                next_action_webhook:
                  type: string
                  format: uri
                  description: API endpoint of the next GPT module (e.g., Market GAP Analysis)
              required:
                - session_id
                - email
                - files
                - next_action_webhook
      responses:
        "200":
          description: IT Assessment request accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Assessment started

  /send_result:
    post:
      operationId: sendResult
      summary: Send output files to the next GPT module
      description: >
        Delivers DOCX, PPTX, and XLSX output to the next module such as Market GAP Analysis.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                gpt_module:
                  type: string
                  enum: [it_assessment]
                status:
                  type: string
                  example: complete
                message:
                  type: string
                  description: Optional status message
                file_1_name:
                  type: string
                file_1_url:
                  type: string
                  format: uri
                file_2_name:
                  type: string
                file_2_url:
                  type: string
                  format: uri
                file_3_name:
                  type: string
                file_3_url:
                  type: string
                  format: uri
                file_4_name:
                  type: string
                file_4_url:
                  type: string
                  format: uri
              required:
                - session_id
                - gpt_module
                - status
                - file_1_name
                - file_1_url
      responses:
        "200":
          description: Output acknowledged
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Files uploaded and status acknowledged

  /notify_zip_delivery:
    post:
      operationId: notifyZipDelivery
      summary: Final ZIP delivery notification
      description: >
        Informs the system that the full bundle ZIP has been delivered to the user
        and the session can be marked complete.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                zip_url:
                  type: string
                  format: uri
              required:
                - session_id
                - zip_url
      responses:
        "200":
          description: ZIP delivery acknowledged
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Final ZIP delivered and session closed
