openapi: 3.1.0
info:
  title: GPT Orchestration API – IT Assessment Module
  version: 2.0.0
  description: API for receiving IT assessment requests and submitting result files to the next module.

servers:
  - url: https://it-assessment-api.onrender.com

paths:
  /start_assessment:
    post:
      operationId: startAssessment
      summary: Trigger IT Assessment processing
      description: Starts the IT Assessment module using session metadata and uploaded infrastructure files.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  description: Unique session identifier (e.g., Temp_20240519_email)
                email:
                  type: string
                  format: email
                  description: User's email address
                files:
                  type: array
                  description: List of input files (inventory, logs, intake, etc.)
                  items:
                    type: object
                    properties:
                      file_name:
                        type: string
                      file_url:
                        type: string
                        format: uri
                      type:
                        type: string
                        enum:
                          - asset_inventory
                          - gap_working
                          - intake
                          - log
                    required:
                      - file_name
                      - file_url
                      - type
                next_action_webhook:
                  type: string
                  format: uri
                  description: Webhook to forward output after processing
              required:
                - session_id
                - email
                - files
                - next_action_webhook
      responses:
        "200":
          description: IT Assessment request accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Assessment started

  /send_result:
    post:
      operationId: sendAssessmentResult
      summary: Return IT Assessment outputs
      description: Sends final output files (DOCX, PPTX, Excel) to the next GPT or Make.com webhook.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                gpt_module:
                  type: string
                  enum:
                    - it_assessment
                file_name:
                  type: string
                file_url:
                  type: string
                  format: uri
                file_2_name:
                  type: string
                file_2_url:
                  type: string
                  format: uri
                file_3_name:
                  type: string
                file_3_url:
                  type: string
                  format: uri
                file_4_name:
                  type: string
                file_4_url:
                  type: string
                  format: uri
                status:
                  type: string
                  example: complete
                message:
                  type: string
              required:
                - session_id
                - gpt_module
                - status
                - file_name
                - file_url
      responses:
        "200":
          description: Files successfully delivered
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Files uploaded and status acknowledged

  /notify_zip_delivery:
    post:
      operationId: notifyZipDelivery
      summary: Final ZIP delivery and session closure
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                zip_url:
                  type: string
                  format: uri
              required:
                - session_id
                - zip_url
      responses:
        "200":
          description: ZIP delivery acknowledged
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Final ZIP delivered and session closed
