openapi: 3.1.0
info:
  title: GPT Orchestration API – IT Assessment Module
  version: 2.0.0
  description: >
    API for receiving IT assessment requests from GPT1, analyzing uploaded infrastructure files,
    performing GAP analysis, classification, scoring, chart generation, and forwarding detailed 
    assessment output (DOCX, PPTX, XLSX) to the next GPT module (e.g., Market GAP Analysis).

servers:
  - url: https://it-assessment-api.onrender.com

paths:
  /start_assessment:
    post:
      operationId: startAssessment
      summary: Trigger IT Assessment Analysis
      description: >
        Receives a session payload including uploaded infrastructure files, begins asynchronous 
        GAP analysis using classification models and templates, and generates reports before 
        forwarding results to the next module.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  description: Unique session identifier (e.g., Temp_20250528_user@example.com)
                email:
                  type: string
                  format: email
                  description: Email address for report delivery
                goal:
                  type: string
                  description: User-defined IT modernization or transformation goal
                files:
                  type: array
                  minItems: 1
                  description: Uploaded infrastructure files for assessment
                  items:
                    type: object
                    properties:
                      file_name:
                        type: string
                      file_url:
                        type: string
                        format: uri
                      type:
                        type: string
                        enum: [
                          asset_inventory, gap_working, intake, log,
                          capacity_plan, compliance_report, firewall_rules,
                          backup_schedule, strategy_input, general
                        ]
                    required: [file_name, file_url, type]
                next_action_webhook:
                  type: string
                  format: uri
              required: [session_id, email, goal, files, next_action_webhook]
      responses:
        '200':
          description: Assessment initiated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Assessment started

  /files/{filename}:
    get:
      operationId: serveGeneratedFile
      summary: Access Generated Assessment File
      description: Returns generated XLSX, DOCX, or PPTX files for download by filename.
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File successfully returned
        '404':
          description: File not found

  /send_result:
    post:
      operationId: sendResultToNextModule
      summary: Send Final Assessment Results
      description: >
        POSTs the final generated report files (HW/SW GAP XLSX, DOCX, PPTX) to the next GPT 
        module as part of the transformation chain.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                gpt_module:
                  type: string
                  enum: [it_assessment]
                status:
                  type: string
                  enum: [complete, error]
                message:
                  type: string
                file_1_name:
                  type: string
                file_1_url:
                  type: string
                  format: uri
                file_2_name:
                  type: string
                file_2_url:
                  type: string
                  format: uri
                file_3_name:
                  type: string
                file_3_url:
                  type: string
                  format: uri
                file_4_name:
                  type: string
                file_4_url:
                  type: string
                  format: uri
              required: [session_id, gpt_module, status, file_1_name, file_1_url]
      responses:
        '200':
          description: Output accepted by next module

  /notify_zip_delivery:
    post:
      operationId: notifyZipDelivery
      summary: Final ZIP Notification
      description: Endpoint for Summarizer GPT to notify ZIP delivery and session completion.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                zip_url:
                  type: string
                  format: uri
              required: [session_id, zip_url]
      responses:
        '200':
          description: Delivery acknowledged
