openapi: 3.1.0
info:
  title: GPT Orchestration API - IT Advisor
  version: 1.2.0

servers:
  - url: https://gpt1-proxy.onrender.com

paths:
  /start_analysis:
    post:
      operationId: startAnalysis
      summary: Initiates intake session and creates Drive folder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                goal:
                  type: string
      responses:
        "200":
          description: Session created

  /list_files:
    post:
      operationId: listFiles
      summary: Lists all files uploaded for a session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                email:
                  type: string
      responses:
        "200":
          description: File list returned

  /trigger_assessment:
    post:
      operationId: triggerAssessment
      summary: Triggers GPT2 to begin infrastructure assessment (manual confirmation required)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
      responses:
        "200":
          description: Assessment successfully triggered

