openapi: 3.1.0
info:
  title: IT Strategy API
  version: 1.0.0
  description: |
    API to generate IT Infrastructure Upgrade Strategy and Executive Report
    based on the current HW/SW state and market GAP data.

servers:
  - url: https://it-strategy-api.onrender.com

paths:
  /start_it_strategy:
    post:
      summary: Start IT Infrastructure Strategy Generation
      operationId: startITStrategy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - session_id
                - email
                - files
              properties:
                session_id:
                  type: string
                  description: Unique session ID (e.g., Temp_YYYYMMDD_email)
                email:
                  type: string
                  description: User's email address
                gpt_module:
                  type: string
                  description: Module name ("it_strategy")
                status:
                  type: string
                  description: Processing status (e.g., "complete")
                files:
                  type: array
                  description: List of files received from the previous GPT
                  items:
                    type: object
                    required:
                      - file_name
                      - file_url
                      - file_type
                    properties:
                      file_name:
                        type: string
                      file_url:
                        type: string
                      file_type:
                        type: string
      responses:
        "200":
          description: IT Strategy generation started successfully
        "500":
          description: Internal server error
